spring:
  application:
    name: memes
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysqlUrl:jdbc:mysql://localhost:3306/memes}
    username: ${mysqlUser:root}
    password: ${mysqlPassword:root}
  web:
    resources:
      static-locations: [ "classpath:/static/","file:./memes/" ]
  webflux:
    static-path-pattern: /static/**

urlPrefix: ${urlPrefix:http://100.68.68.47:8080/}

token: ${token}

