spring:
  application:
    name: memes
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysqlUrl}
    username: ${mysqlUser}
    password: ${mysqlPassword}
  web:
    resources:
      static-locations: [ "classpath:/static/","file:./memes/" ]
  webflux:
    static-path-pattern: /static/**

urlPrefix: ${urlPrefix}

token: ${token}

