// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media_type.proto

// Protobuf Java Version: 3.25.3
package com.memes.model.transport;

public final class MediaTypeOuterClass {
    private MediaTypeOuterClass() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
            "\n\020media_type.proto* \n\tMediaType\022\t\n\005IMAGE" +
                "\020\000\022\010\n\004TEXT\020\001B\035\n\031com.memes.model.transpor" +
                "tP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(
                descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
