// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

// Protobuf Java Version: 3.25.1
package com.memes.model.transport;

/**
 * Protobuf enum {@code OperationType}
 */
public enum OperationType
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DELETE = 0;</code>
     */
    DELETE(0),
    /**
     * <code>CACHE = 1;</code>
     */
    CACHE(1), UNRECOGNIZED(-1),
    ;

    /**
     * <code>DELETE = 0;</code>
     */
    public static final int DELETE_VALUE = 0;
    /**
     * <code>CACHE = 1;</code>
     */
    public static final int CACHE_VALUE = 1;

    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value
     *            The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OperationType valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value
     *            The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OperationType forNumber(int value) {
        switch (value) {
            case 0:
                return DELETE;
            case 1:
                return CACHE;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationType> internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<OperationType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
        public OperationType findValueByNumber(int number) {
            return OperationType.forNumber(number);
        }
    };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                    "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return com.memes.model.transport.Control.getDescriptor().getEnumTypes().get(0);
    }

    private static final OperationType[] VALUES = values();

    public static OperationType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OperationType)
}
