// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: embedding.proto

// Protobuf Java Version: 3.25.1
package com.bupt.memes.model.transport;

public interface EmbeddingOrBuilder extends
		// @@protoc_insertion_point(interface_extends:Embedding)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string id = 1;</code>
	 * 
	 * @return The id.
	 */
	java.lang.String getId();

	/**
	 * <code>string id = 1;</code>
	 * 
	 * @return The bytes for id.
	 */
	com.google.protobuf.ByteString getIdBytes();

	/**
	 * <code>int64 timestamp = 2;</code>
	 * 
	 * @return The timestamp.
	 */
	long getTimestamp();

	/**
	 * <code>repeated float data = 3;</code>
	 * 
	 * @return A list containing the data.
	 */
	java.util.List<java.lang.Float> getDataList();

	/**
	 * <code>repeated float data = 3;</code>
	 * 
	 * @return The count of data.
	 */
	int getDataCount();

	/**
	 * <code>repeated float data = 3;</code>
	 * 
	 * @param index
	 *            The index of the element to return.
	 * @return The data at the given index.
	 */
	float getData(int index);
}
