// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media.proto

// Protobuf Java Version: 3.25.1
package com.bupt.memes.model.transport;

/**
 * Protobuf type {@code MediaMessage}
 */
public final class MediaMessage extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:MediaMessage)
		MediaMessageOrBuilder {
	private static final long serialVersionUID = 0L;

	// Use MediaMessage.newBuilder() to construct.
	private MediaMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private MediaMessage() {
		id_ = "";
		mediaType_ = 0;
		data_ = com.google.protobuf.ByteString.EMPTY;
	}

	@java.lang.Override
	@SuppressWarnings({ "unused" })
	protected java.lang.Object newInstance(
			UnusedPrivateParameter unused) {
		return new MediaMessage();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.bupt.memes.model.transport.Media.internal_static_MediaMessage_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.bupt.memes.model.transport.Media.internal_static_MediaMessage_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						com.bupt.memes.model.transport.MediaMessage.class, com.bupt.memes.model.transport.MediaMessage.Builder.class);
	}

	public static final int ID_FIELD_NUMBER = 1;
	@SuppressWarnings("serial")
	private volatile java.lang.Object id_ = "";

	/**
	 * <code>string id = 1;</code>
	 * 
	 * @return The id.
	 */
	@java.lang.Override
	public java.lang.String getId() {
		java.lang.Object ref = id_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			id_ = s;
			return s;
		}
	}

	/**
	 * <code>string id = 1;</code>
	 * 
	 * @return The bytes for id.
	 */
	@java.lang.Override
	public com.google.protobuf.ByteString getIdBytes() {
		java.lang.Object ref = id_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
					(java.lang.String) ref);
			id_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int TIMESTAMP_FIELD_NUMBER = 2;
	private long timestamp_ = 0L;

	/**
	 * <code>int64 timestamp = 2;</code>
	 * 
	 * @return The timestamp.
	 */
	@java.lang.Override
	public long getTimestamp() {
		return timestamp_;
	}

	public static final int MEDIATYPE_FIELD_NUMBER = 3;
	private int mediaType_ = 0;

	/**
	 * <code>.MediaType mediaType = 3;</code>
	 * 
	 * @return The enum numeric value on the wire for mediaType.
	 */
	@java.lang.Override
	public int getMediaTypeValue() {
		return mediaType_;
	}

	/**
	 * <code>.MediaType mediaType = 3;</code>
	 * 
	 * @return The mediaType.
	 */
	@java.lang.Override
	public com.bupt.memes.model.transport.MediaType getMediaType() {
		com.bupt.memes.model.transport.MediaType result = com.bupt.memes.model.transport.MediaType.forNumber(mediaType_);
		return result == null ? com.bupt.memes.model.transport.MediaType.UNRECOGNIZED : result;
	}

	public static final int DATA_FIELD_NUMBER = 4;
	private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

	/**
	 * <code>bytes data = 4;</code>
	 * 
	 * @return The data.
	 */
	@java.lang.Override
	public com.google.protobuf.ByteString getData() {
		return data_;
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
		}
		if (timestamp_ != 0L) {
			output.writeInt64(2, timestamp_);
		}
		if (mediaType_ != com.bupt.memes.model.transport.MediaType.IMAGE.getNumber()) {
			output.writeEnum(3, mediaType_);
		}
		if (!data_.isEmpty()) {
			output.writeBytes(4, data_);
		}
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
		}
		if (timestamp_ != 0L) {
			size += com.google.protobuf.CodedOutputStream
					.computeInt64Size(2, timestamp_);
		}
		if (mediaType_ != com.bupt.memes.model.transport.MediaType.IMAGE.getNumber()) {
			size += com.google.protobuf.CodedOutputStream
					.computeEnumSize(3, mediaType_);
		}
		if (!data_.isEmpty()) {
			size += com.google.protobuf.CodedOutputStream
					.computeBytesSize(4, data_);
		}
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof com.bupt.memes.model.transport.MediaMessage)) {
			return super.equals(obj);
		}
		com.bupt.memes.model.transport.MediaMessage other = (com.bupt.memes.model.transport.MediaMessage) obj;

		if (!getId()
				.equals(other.getId()))
			return false;
		if (getTimestamp() != other.getTimestamp())
			return false;
		if (mediaType_ != other.mediaType_)
			return false;
		if (!getData()
				.equals(other.getData()))
			return false;
		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + ID_FIELD_NUMBER;
		hash = (53 * hash) + getId().hashCode();
		hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
		hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
				getTimestamp());
		hash = (37 * hash) + MEDIATYPE_FIELD_NUMBER;
		hash = (53 * hash) + mediaType_;
		hash = (37 * hash) + DATA_FIELD_NUMBER;
		hash = (53 * hash) + getData().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
	}

	public static com.bupt.memes.model.transport.MediaMessage parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.bupt.memes.model.transport.MediaMessage prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE
				? new Builder()
				: new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code MediaMessage}
	 */
	public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:MediaMessage)
			com.bupt.memes.model.transport.MediaMessageOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.bupt.memes.model.transport.Media.internal_static_MediaMessage_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.bupt.memes.model.transport.Media.internal_static_MediaMessage_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.bupt.memes.model.transport.MediaMessage.class, com.bupt.memes.model.transport.MediaMessage.Builder.class);
		}

		// Construct using com.bupt.memes.model.transport.MediaMessage.newBuilder()
		private Builder() {

		}

		private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			bitField0_ = 0;
			id_ = "";
			timestamp_ = 0L;
			mediaType_ = 0;
			data_ = com.google.protobuf.ByteString.EMPTY;
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.bupt.memes.model.transport.Media.internal_static_MediaMessage_descriptor;
		}

		@java.lang.Override
		public com.bupt.memes.model.transport.MediaMessage getDefaultInstanceForType() {
			return com.bupt.memes.model.transport.MediaMessage.getDefaultInstance();
		}

		@java.lang.Override
		public com.bupt.memes.model.transport.MediaMessage build() {
			com.bupt.memes.model.transport.MediaMessage result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public com.bupt.memes.model.transport.MediaMessage buildPartial() {
			com.bupt.memes.model.transport.MediaMessage result = new com.bupt.memes.model.transport.MediaMessage(this);
			if (bitField0_ != 0) {
				buildPartial0(result);
			}
			onBuilt();
			return result;
		}

		private void buildPartial0(com.bupt.memes.model.transport.MediaMessage result) {
			int from_bitField0_ = bitField0_;
			if (((from_bitField0_ & 0x00000001) != 0)) {
				result.id_ = id_;
			}
			if (((from_bitField0_ & 0x00000002) != 0)) {
				result.timestamp_ = timestamp_;
			}
			if (((from_bitField0_ & 0x00000004) != 0)) {
				result.mediaType_ = mediaType_;
			}
			if (((from_bitField0_ & 0x00000008) != 0)) {
				result.data_ = data_;
			}
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.bupt.memes.model.transport.MediaMessage) {
				return mergeFrom((com.bupt.memes.model.transport.MediaMessage) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.bupt.memes.model.transport.MediaMessage other) {
			if (other == com.bupt.memes.model.transport.MediaMessage.getDefaultInstance())
				return this;
			if (!other.getId().isEmpty()) {
				id_ = other.id_;
				bitField0_ |= 0x00000001;
				onChanged();
			}
			if (other.getTimestamp() != 0L) {
				setTimestamp(other.getTimestamp());
			}
			if (other.mediaType_ != 0) {
				setMediaTypeValue(other.getMediaTypeValue());
			}
			if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
				setData(other.getData());
			}
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							id_ = input.readStringRequireUtf8();
							bitField0_ |= 0x00000001;
							break;
						} // case 10
						case 16: {
							timestamp_ = input.readInt64();
							bitField0_ |= 0x00000002;
							break;
						} // case 16
						case 24: {
							mediaType_ = input.readEnum();
							bitField0_ |= 0x00000004;
							break;
						} // case 24
						case 34: {
							data_ = input.readBytes();
							bitField0_ |= 0x00000008;
							break;
						} // case 34
						default: {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			} finally {
				onChanged();
			} // finally
			return this;
		}

		private int bitField0_;

		private java.lang.Object id_ = "";

		/**
		 * <code>string id = 1;</code>
		 * 
		 * @return The id.
		 */
		public java.lang.String getId() {
			java.lang.Object ref = id_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				id_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string id = 1;</code>
		 * 
		 * @return The bytes for id.
		 */
		public com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
						(java.lang.String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string id = 1;</code>
		 * 
		 * @param value
		 *            The id to set.
		 * @return This builder for chaining.
		 */
		public Builder setId(
				java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			id_ = value;
			bitField0_ |= 0x00000001;
			onChanged();
			return this;
		}

		/**
		 * <code>string id = 1;</code>
		 * 
		 * @return This builder for chaining.
		 */
		public Builder clearId() {
			id_ = getDefaultInstance().getId();
			bitField0_ = (bitField0_ & ~0x00000001);
			onChanged();
			return this;
		}

		/**
		 * <code>string id = 1;</code>
		 * 
		 * @param value
		 *            The bytes for id to set.
		 * @return This builder for chaining.
		 */
		public Builder setIdBytes(
				com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);
			id_ = value;
			bitField0_ |= 0x00000001;
			onChanged();
			return this;
		}

		private long timestamp_;

		/**
		 * <code>int64 timestamp = 2;</code>
		 * 
		 * @return The timestamp.
		 */
		@java.lang.Override
		public long getTimestamp() {
			return timestamp_;
		}

		/**
		 * <code>int64 timestamp = 2;</code>
		 * 
		 * @param value
		 *            The timestamp to set.
		 * @return This builder for chaining.
		 */
		public Builder setTimestamp(long value) {

			timestamp_ = value;
			bitField0_ |= 0x00000002;
			onChanged();
			return this;
		}

		/**
		 * <code>int64 timestamp = 2;</code>
		 * 
		 * @return This builder for chaining.
		 */
		public Builder clearTimestamp() {
			bitField0_ = (bitField0_ & ~0x00000002);
			timestamp_ = 0L;
			onChanged();
			return this;
		}

		private int mediaType_ = 0;

		/**
		 * <code>.MediaType mediaType = 3;</code>
		 * 
		 * @return The enum numeric value on the wire for mediaType.
		 */
		@java.lang.Override
		public int getMediaTypeValue() {
			return mediaType_;
		}

		/**
		 * <code>.MediaType mediaType = 3;</code>
		 * 
		 * @param value
		 *            The enum numeric value on the wire for mediaType to set.
		 * @return This builder for chaining.
		 */
		public Builder setMediaTypeValue(int value) {
			mediaType_ = value;
			bitField0_ |= 0x00000004;
			onChanged();
			return this;
		}

		/**
		 * <code>.MediaType mediaType = 3;</code>
		 * 
		 * @return The mediaType.
		 */
		@java.lang.Override
		public com.bupt.memes.model.transport.MediaType getMediaType() {
			com.bupt.memes.model.transport.MediaType result = com.bupt.memes.model.transport.MediaType.forNumber(mediaType_);
			return result == null ? com.bupt.memes.model.transport.MediaType.UNRECOGNIZED : result;
		}

		/**
		 * <code>.MediaType mediaType = 3;</code>
		 * 
		 * @param value
		 *            The mediaType to set.
		 * @return This builder for chaining.
		 */
		public Builder setMediaType(com.bupt.memes.model.transport.MediaType value) {
			if (value == null) {
				throw new NullPointerException();
			}
			bitField0_ |= 0x00000004;
			mediaType_ = value.getNumber();
			onChanged();
			return this;
		}

		/**
		 * <code>.MediaType mediaType = 3;</code>
		 * 
		 * @return This builder for chaining.
		 */
		public Builder clearMediaType() {
			bitField0_ = (bitField0_ & ~0x00000004);
			mediaType_ = 0;
			onChanged();
			return this;
		}

		private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

		/**
		 * <code>bytes data = 4;</code>
		 * 
		 * @return The data.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString getData() {
			return data_;
		}

		/**
		 * <code>bytes data = 4;</code>
		 * 
		 * @param value
		 *            The data to set.
		 * @return This builder for chaining.
		 */
		public Builder setData(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			data_ = value;
			bitField0_ |= 0x00000008;
			onChanged();
			return this;
		}

		/**
		 * <code>bytes data = 4;</code>
		 * 
		 * @return This builder for chaining.
		 */
		public Builder clearData() {
			bitField0_ = (bitField0_ & ~0x00000008);
			data_ = getDefaultInstance().getData();
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:MediaMessage)
	}

	// @@protoc_insertion_point(class_scope:MediaMessage)
	private static final com.bupt.memes.model.transport.MediaMessage DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.bupt.memes.model.transport.MediaMessage();
	}

	public static com.bupt.memes.model.transport.MediaMessage getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<MediaMessage> PARSER = new com.google.protobuf.AbstractParser<MediaMessage>() {
		@java.lang.Override
		public MediaMessage parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			} catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<MediaMessage> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<MediaMessage> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public com.bupt.memes.model.transport.MediaMessage getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
