// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Media.proto

package com.bupt.memes.model.transport;

/**
 * Protobuf enum {@code MediaType}
 */
public enum MediaType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>IMAGE = 0;</code>
   */
  IMAGE(0),
  /**
   * <code>TEXT = 1;</code>
   */
  TEXT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>IMAGE = 0;</code>
   */
  public static final int IMAGE_VALUE = 0;
  /**
   * <code>TEXT = 1;</code>
   */
  public static final int TEXT_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MediaType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MediaType forNumber(int value) {
    switch (value) {
      case 0: return IMAGE;
      case 1: return TEXT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MediaType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MediaType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MediaType>() {
          public MediaType findValueByNumber(int number) {
            return MediaType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bupt.memes.model.transport.Media.getDescriptor().getEnumTypes().get(0);
  }

  private static final MediaType[] VALUES = values();

  public static MediaType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MediaType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MediaType)
}

